- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  win_chocolatey:
    name: chocolatey

- name: Add Nuget provider (requirement for Pscx)
  ansible.windows.win_shell: Install-PackageProvider -Name Nuget -Force

- name: Add a PowerShell Community Extensions module
  community.windows.win_psmodule:
    name: Pscx
    state: present
    accept_license: true
    allow_clobber : true