eoc_temp_dir: 'C:\Temp'

eoc_client_url : https://unreal-template-dev.s3.eu-west-1.amazonaws.com/EdgeOfChaos-develop-Shipping.7z
eoc_client_archive : '{{ eoc_temp_dir }}\eoc.7z'
eoc_client_dest : 'C:\EoC\Build'

eoc_scripts_url : https://unreal-template-dev.s3.eu-west-1.amazonaws.com/Scripts_20240620.7z
eoc_scripts_archive : '{{ eoc_temp_dir }}\eoc_scripts.7z'
eoc_scripts_dest : 'C:\EoC'
eoc_scripts_config_bots_path : 'C:\EoC\Scripts\Runners\config_bots.json'

bot_configuration: 'Cinematic_spawn_1-5'
command_line_file: '{{ role_path }}/files/{{ bot_configuration }}.json'