- name: Ensure quark directory exists
  file:
    path: "{{ quark_dir }}"
    state: directory

- name: Clone Git repository
  ansible.builtin.git:
    repo: "https://{{ git_quark_pat }}@{{ git_repo_url }}"
    version: "{{ git_branch }}"
    dest: "{{ quark_dir }}"
