- name: Modify hard nofile limits for wildcard domain
  become: true
  community.general.pam_limits:
    domain: "*"
    limit_type: hard
    limit_item: nofile
    value: 1048576

- name: Modify soft nofile limits for wildcard domain
  become: true
  community.general.pam_limits:
    domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 1048576

- name: Increase kernel socket buffer size
  become: true
  ansible.posix.sysctl:
    reload: true
    name: "{{ item }}"
    value: 250000000
    sysctl_set: true
    state: present
  loop:
    - net.core.rmem_max
    - net.core.rmem_default
    - net.core.wmem_max
    - net.core.wmem_default

# Restart the session for the limits.conf values to be applied
- name: reset ssh connection
  meta: reset_connection
