- name: Include common vars
  ansible.builtin.include_vars: ../vars.yml

- name: Install prereqs
  ansible.builtin.include_tasks: prereqs.yml

- name: Configure fileno limits and socket buffers
  ansible.builtin.include_tasks: limits.yml

- name: Clone Quark repository
  ansible.builtin.include_tasks: clone.yml
