- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install build-essential
  ansible.builtin.apt:
    name: build-essential
    state: present
  become: true

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Install capnproto
  ansible.builtin.apt:
    name: capnproto
    state: present
  become: true

- name: Install libssl-dev
  ansible.builtin.apt:
    name: libssl-dev
    state: present
  become: true

- name: Install pkg-config
  ansible.builtin.apt:
    name: pkg-config
    state: present
  become: true

- name: Check if cargo is installed
  shell: command -v ~/.cargo/bin/cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
