- name: Include win_host
  ansible.builtin.include_role:
    name: win_host

- name: Include vars
  ansible.builtin.include_vars: ../vars.yml

- name: Create temp directory 
  ansible.windows.win_file:
    path:  '{{ eoc_temp_dir }}'
    state: directory

- name: Include dependencies
  ansible.builtin.include_tasks: ./dependencies.yml

- name: Include install_client
  ansible.builtin.include_tasks: ./install_client.yml

- name: Include install_scripts
  ansible.builtin.include_tasks: ./install_scripts.yml

- name: Include install_service
  ansible.builtin.include_tasks: ./install_service.yml