- name: Include vars
  ansible.builtin.include_vars: ../vars.yml

- name: Include common role
  ansible.builtin.include_role:
    name: common

- name: Clone Quark bots
  ansible.builtin.include_tasks: clone.yml

- name: Build Quark bots
  ansible.builtin.include_tasks: build.yml

- name: Install Quark Bots service
  ansible.builtin.include_tasks: service.yml
