- name: Create systemd service file
  ansible.builtin.template:
    src: ../templates/bots.service.j2
    dest: /etc/systemd/system/bots.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable and start the service
  ansible.builtin.systemd:
    name: bots
    state: restarted
    enabled: true
  become: true
