---
- name: Setup EoC Bots
  hosts: eoc_bots
  # Disable gather_facts as ssh won't be ready yet
  gather_facts: no
  roles:
    - eoc_bots
  pre_tasks:
    - name: Import windows pretask
      include_tasks: 'pretask_windows.yaml'

# "{{ groups['eoc_bots'] }}"
