- name: Configure Quark servers
  hosts: quark_servers
  roles:
    - quark_server

- name: Update package cache on Debian/Ubuntu systems
  hosts: grafana
  become: true
  tasks:
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      ansible.builtin.apt:
        update_cache: yes

- name: Install Docker and Docker Compose
  hosts: grafana
  become: yes
  roles:
    - grafana_prometheus

# "{{ groups['quark_servers'] }}"