---
# tasks file for grafana_prometheus

# https://github.com/geerlingguy/ansible-role-pip/issues/49#issuecomment-1849023975
- name: Populate Apt's Cache with package definitions to avoid "no such package" errors
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: include geerlingguy.pip role
  ansible.builtin.import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
        - name: docker
        - name: docker-compose

- name: include geerlingguy.docker role
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: Copy files from submodule
  ansible.builtin.copy:
    src: "{{ role_path }}/files/Grafana-Docker-Deployment/docker-compose"
    dest: /home/{{ ansible_user }}/grafana-prometheus
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy templated prometheus config
  ansible.builtin.template:
    src: "{{ role_path }}/templates/prometheus.j2"
    dest: /home/{{ ansible_user }}/grafana-prometheus/docker-compose/prometheus.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: (re)Start grafana and prometheus services
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/grafana-prometheus/docker-compose/