#!/bin/bash
# Function to display help information

help() {
    echo "Usage: $0 COMMAND [OPTIONS]"
    echo ""
    echo "Commands:"
    echo "  create - Initializes and provisions a new server."
    echo "    Options:"
    echo "      -project <project_name>      Specify the project name for the server."
    echo "      -size <instance_size>        Specify the size of the server instance (Default: 'medium')."
    echo "      -count <instance_count>      Specify the number of instances to create (Default: 1)."
    echo "      -cloud <cloud_provider>      Specify the cloud provider (e.g., 'aws', 'gcp', 'azure')."
    echo "      -repo <git_repository>       Specify the Git repository URL for configuration."
    echo "      -branch <git_branch>         Specify the branch to use from the Git repository (Default: 'master')."
    echo "      -region <region>             Specify the region where the server will be created (Default depends on provider)."
    echo ""
    echo "  destroy - Terminates a server identified by its UUID."
    echo "    Options:"
    echo "      -id <UUID>                   Specify the UUID of the server to destroy."
    echo ""
    echo "  show - Displays information about a server identified by its UUID."
    echo "    Options:"
    echo "      -id <UUID>                   Specify the UUID of the server to display information for."
    echo ""
    echo "  help - Displays this help information."
    echo ""
    echo "Examples:"
    echo "  $0 create -project MyProject -size large -count 2 -cloud aws -repo https://github.com/myrepo -branch develop -region us-west-2"
    echo "  $0 destroy -id 123e4567-e89b-12d3-a456-426614174000"
    echo "  $0 show -id 123e4567-e89b-12d3-a456-426614174000"
    echo ""
    echo "Available Modules: ${MODULES[*]}"
}

