variable "region" {}
variable "resource_group_name" {}
variable "dedicated_host_group_name" {}
variable "dedicated_host_name" {}
variable "vm_size" {}
variable "instance_count" {}
variable "admin_username" {}
variable "admin_ssh_key" {}
variable "subnet_internal_id" {}
variable "subnet_external_id" {}
variable "public_ip_id" {}
