name: Validate Terraform configurations
on: []

env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  validate-packer-configuration:
    strategy:
      matrix:
        packer-config: [agents, bots, elastic_ips, lb, network, quark]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Validate ${{ matrix.packer-config }}
        run: |
          cd environment/dev/whole/${{ matrix.packer-config }}
          terraform init
          terraform validate
